---
- name: Make Surveys based on backup directories
  hosts: tower
  gather_facts: no
  vars_files:
    - default_vars.yml
    - ./credentials/tower-credentials.yml

  tasks:
    - name: Find /tmp/ios_backups/ all directories, exclude nginx and mysql
      find:
        paths: /tmp/ios_backups/
        recurse: no
        file_type: directory
      register: find_output


    # - debug:
    #     var: find_output

    # - debug:
    #     msg: "{{ item.path }}"
    #   loop: "{{ find_output.files }}"

    - name: Build survey_spec from template
      template:
        src: ./templates/backup_survey.j2
        dest: /tmp/survey.json
      # delegate_to: localhost

    - name: Build Ansible Tower template with Survey
      tower_job_template:
          name: "IOS Check for Configuration Drift"
          job_type: "run"
          inventory: "IOS Github-sourced Routers"
          project: "Ansible IOS Demo Exercises"
          playbook: "ios-drift-detect.yml"
          credential: "maf-ios-demo-private"
          survey_enabled: true
          survey_spec: "{{ lookup('template', '/tmp/survey.json') }}"
          tower_username: "{{ TOWER_USERNAME }}"
          tower_password: "{{ TOWER_PASSWORD }}"
          tower_host: https://ansibletower.michaelanthonyford.com
          validate_certs: no
      delegate_to: localhost
      run_once: yes

    # - name: Clear existing backups from ios_backups directory
    #   file:
    #     state: absent
    #     path: ~/ios_backups/
    #
    # - name: Copy backups to webserver
    #   copy:
    #     src: /tmp/ios_backups/
    #     dest: ~/ios_backups/
