---
- name: Add loopback interfaces
  hosts: ios
  connection: network_cli
  gather_facts: no

  tasks:

  - name: Add loopback interfaces using aggregate
    debug:
      var: "{{ lookup('file', './data/resource_modules/loopbacks.json') | to_nice_yaml }}"
    tags: debug

  - name: Add loopback interfaces using aggregate
    ios_l3_interfaces:
      config: "{{ lookup('file', './data/resource_modules/loopbacks.json') | to_nice_yaml }}"
      state: merged
    tags: run
