---
- name: Restore router configurations from archive
  hosts: ios
  connection: network_cli
  gather_facts: no

  tasks:

  - name: Copy archived config to router and config replace
    ios_config:
      src: "{{ playbook_dir }}/backup/{{inventory_hostname}}.config"
