---
- name: Add Loopback L3 Interfaces
  hosts: ios
  connection: network_cli
  gather_facts: no
  vars:
    - merge: true

  tasks:

  - name: Add loopback interfaces using aggregate
    ios_l3_interfaces:
      config: "{{ lookup('file', './data/resource_modules/loopbacks.yml') }}"
      state: merged
    when: merge
