---
- name: Populate Service Now CMDB with Network elements
  hosts: ios
  gather_facts: no
  connection: network_cli
  # vars:
  #   populate_cmdb: true
  vars_files:
    - default_vars.yml
    - {{ playbook_dir }}/credentials/servicenow-credentials.yml

  tasks:

  - name: set vendor fact by network platform
    block:
      - name: Set vendor fact to cisco
        set_fact: vendor="cisco"

      - name: Gather facts
        ios_facts:
          gather_subset: all
    when: ansible_network_os == "ios"


  - name: Create a network host record for "{{ inventory_hostname }}"
    snow_record:
      state: present
      table: cmdb_ci_netgear
      username: "{{ SN_USERNAME }}"
      password: "{{ SN_PASSWORD }}"
      instance: "{{ SN_INSTANCE }}"
      data:
        name: "{{ inventory_hostname }}"
        manufacturer: "{{ vendor }}"
        firmware_manufacturer: "{{ vendor }}"
        device_type: router
        model_number: "{{ ansible_facts.net_model }}"
        assigned_to: "Michael Hoefer"
        firmware_version: "{{ ansible_facts.net_version }}"
        serial_number: "{{ ansible_facts.net_serialnum }}"
        ip_address: "{{ ansible_host }}"
        mac_address: '{{ ansible_facts.net_interfaces["GigabitEthernet1"].macaddress }}'
        ports: '{{ ansible_facts.net_interfaces["GigabitEthernet1"].mediatype }}'
    register: new_host

  # - debug: var=new_host.record
  # - debug: var=ansible_facts

  # - name: include vars
  #   include_role:
  #     name: michaelford85.ansible_servicenow_cmdb
