---
- name: Add Loopback L3 Interfaces
  hosts: ios
  connection: network_cli
  gather_facts: no
  vars_files:
    - ./data/resource_modules/loopbacks.yml
  vars:
    - thestate: merged

  tasks:

  - name: Add loopback interfaces using aggregate
    ios_interfaces:
      config: "{{ loopbacks }}"
      state: merged
    when: thestate == "merged"

  - name: Add loopback interfaces using aggregate
    ios_interfaces:
      config: "{{ loopbacks }}"
      state: deleted
    when: thestate == "deleted"
