---
- name: Gather IOS facts with Network Engine
  hosts: ios
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Collect facts from Cisco IOS elements
      import_role:
        name: ansible-network.cisco_ios
        tasks_from: get_facts
