---
- name: Restore router configurations from archive
  hosts: ios
  connection: network_cli
  gather_facts: no

  tasks:

  - name: Copy locally backed up config to router and config replace
    cli_config:
      config: "{{ lookup('file', './backup/{{ inventory_hostname }}.config') }}"
      replace: yes
