---
- name: Add Loopback L3 Interfaces
  hosts: ios
  connection: network_cli
  gather_facts: no
  vars_files:
    - ./data/resource_modules/loopbacks.yml
  vars:
    - merge: true

  tasks:

  - name: Add loopback interfaces using aggregate
    ios_interfaces:
      config: "{{ loopbacks }}"
      # config:
      #   - name: Loopback20
      #     ipv4:
      #     - address: 10.0.20.1/24
      #   - name: Loopback30
      #     ipv4:
      #     - address: 10.0.30.1/24
      #   - name: Loopback40
      #     ipv4:
      #     - address: 10.0.40.1/24
      #   - name: Loopback50
      #     ipv4:
      #     - address: 10.0.50.1/24
      state: merged
    when: merge
