---
- name: Reload IOS Device
  hosts: ios
  connection: network_cli
  gather_facts: no
  vars:
    connect_timeout: 50
    command_timeout: 50
  vars_files:
    - default_vars.yml

  tasks:

    - name: Gather IOS facts before reload
      ios_facts:

    - name: check the startup-config against the running-config
      ios_config:
        diff_against: startup
        diff_ignore_lines:
          - "Building configuration..."
          - 'Current configuration.*'
      register: modified_output

    - debug:
        var: modified_output

    # - name: Reload router
    #   cli_command:
    #     command: reload
    #     prompt:
    #       - confirm
    #     answer:
    #       - y


    # - name: Wait for router to come back up
    #   wait_for_connection:
    #     connect_timeout: 30
    #     sleep: 10
    #     timeout: 300
    #     delay: 60
    #
    # - name: Gather IOS facts after reload
    #   ios_facts:
    #
    # - name: Print installed OS
    #   debug:
    #     var: ansible_net_version
