---
- name: Check BGP Summary and Log
  hosts: ios
  connection: network_cli
  gather_facts: no
  roles:
    - parse_genie

  tasks:

  - name: show cdp neighbors
    ios_facts:
      gather_subset: interfaces
    register: facts_output

  - name: show ip bgp summary
    ios_command:
      commands:
        # - show bgp all summary
        - show bgp ipv4 unicast neighbors
    register: bgp_sum_output

  - name: show logging
    ios_command:
      commands:
        - show logging
    register: show_log_output

  - name: Filter BGP Summary output through Genie
    set_fact:
      # pyats_bgp_sum: "{{ bgp_sum_output['stdout'][0] | parse_genie(command='show bgp all summary', os='iosxe') }}"
      pyats_bgp_sum: "{{ bgp_sum_output['stdout'][0] | parse_genie(command='show bgp {address_family} neighbors', os='iosxe') }}"

  - name: Debug BGP Summary
    debug:
      var: pyats_bgp_sum

  - name: Print out BGP Neighbors
    debug:
      msg: "BGP Neighbor is {{ item }}"
    loop: "{{ pyats_bgp_sum.list_of_neighbors }}"

  - name: Print out BGP Session State
    debug:
      msg: "The session state for BGP neighbor {{ item }} is {{ pyats_bgp_sum.vrf.default.neighbor. 10.200.200.2.session_state }}"
    loop: "{{ pyats_bgp_sum.list_of_neighbors }}"

  - name: Filter Show Logging output through Genie
    set_fact:
      pyats_show_log: "{{ show_log_output['stdout'][0] | parse_genie(command='show logging', os='iosxe') }}"


  # - name: Debug CDP Neighbors
  #   debug:
  #     var: facts_output.ansible_facts.ansible_net_neighbors
  #
  - name: Debug BGP Summary
    debug:
      var: pyats_bgp_sum

  # - name: "Set BGP VRF fact for {{ bgp_vrf }}"
  #   set_fact:
  #     bgp_neighbors: "{{ pyats_bgp_sum | dict2items }}"
  #
  # - name: "Debug BGP Neighbors for vrf {{ bgp_vrf }}"
  #   debug:
  #     var: bgp_neighbors

  # - name: Print out BGP status for each neighbor
  #   debug:
  #     msg: "{{ bgp_neighbors | json_query('neighbor[*].address_family.ipv4_unicast.state_pfxrcd') }}"

  # - name: Debug Show Logging
  #   debug:
  #     var: pyats_show_log



  - name: CHECK show cdp neighbor
    debug:
      msg: "Router {{ inventory_hostname }} has no CDP neighbors"
    when: facts_output.ansible_facts.ansible_net_neighbors|length == 0


  # - name: Print all Active BGP Neighbors
  #   debug:
  #     msg: "Neighbor: {{ pyats_bgp_sum.vrf.default.neighbor }}"
  #   loop: "{{ pyats_bgp_sum.vrf.default }}"
