---
- name: Add VRF to ios Routers
  hosts: ios
  connection: network_cli
  gather_facts: no
  vars:
    thestate: merged

  tasks:

  - name: "Configure the {{ vrf_name }} vrf"
    ios_vrf:
      name: "{{ vrf_name }}"
      description: "VRF {{ vrf_name }} added by Ansible"
      state: present
    when: thestate == "merged"

  - name: "Remove the {{ vrf_name }} vrf"
    ios_vrf:
      name: "{{ vrf_name }}"
      state: present
    when: thestate == "deleted"
