---
- name: Gather IOS facts
  hosts: "{{ group }}"
  connection: network_cli
  gather_facts: no

  tasks:
  - name: Collect facts from Cisco IOS elements
    ios_facts:
    register: facts_output

  - name: Print out facts
    debug:
      var: facts_output
