---
- name: Check BGP Summary and Log
  hosts: ios
  connection: network_cli
  gather_facts: no
  roles:
    - parse_genie

  tasks:

  - name: show cdp neighbors
    ios_facts:
      gather_subset: interfaces
    register: facts_output

  - name: show ip bgp summary
    ios_command:
      commands:
        - show bgp all summary
    register: bgp_sum_output

  - name: show logging
    ios_command:
      commands:
        - show logging
    register: show_log_output

  - name: Filter BGP Summary output through Genie
    set_fact:
      pyats_bgp_sum: "{{ bgp_sum_output['stdout'][0] | parse_genie(command='show bgp all summary', os='iosxe') }}"

  - name: Filter Show Logging output through Genie
    set_fact:
      pyats_show_log: "{{ show_log_output['stdout'][0] | parse_genie(command='show logging', os='iosxe') }}"

  # - name: Debug CDP Neighbors
  #   debug:
  #     var: facts_output.ansible_facts.ansible_net_neighbors
  #
  - name: Debug BGP Summary
    debug:
      var: pyats_bgp_sum
  #
  # - name: Debug Show Logging
  #   debug:
  #     var: pyats_show_log


  - name: CHECK show cdp neighbor
    debug:
      msg: "Router {{ inventory_hostname }} has no CDP neighbors"
    when: facts_output.ansible_facts.ansible_net_neighbors|length == 0


  - name: "Display all neighbors"
    debug:
      var: item
    loop: "{{ pyats_bgp_sum | json_query('vrf.default[*].neighbor') }}"


  # - name: Print all Active BGP Neighbors
  #   debug:
  #     msg: "Neighbor: {{ pyats_bgp_sum.vrf.default.neighbor }}"
  #   loop: "{{ pyats_bgp_sum.vrf.default }}"
