---
# tasks file for ntp_compliance
- name: Show current ntp servers on device
  ios_command:
    commands: show run | i ntp
  register: output

- name: Print current ntp servers
  debug:
    var: output.stdout_lines

- name: Compare ntp servers and remove erroroneous entries
  ios_config:
    lines: no {{ item }}
  loop: "{{ output.stdout_lines[0] }}"
  when:
    - item not in ntp_servers
    - output.stdout[0].find('ntp') != -1

- name: Ensure intended ntp servers are present
  ios_config:
    lines: "{{ item }}"
  loop: "{{ ntp_servers }}"
